# Tcl script generated by PlanAhead

set tclUtilsPath "C:/Xilinx/13.3/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set cgProjectPath "C:/largework/fpga/kovan/kovan1/kovan1.srcs/sources_1/ip/clk_wiz_v3_2_1/coregen.cgc"

set ipName "clk_wiz_v3_2_1"

set vlnv "xilinx.com:ip:clk_wiz:3.2"

set cgPartSpec "6slx45-2csg324"

set bomFilePath "C:/largework/fpga/kovan/kovan1/kovan1.srcs/sources_1/ip/clk_wiz_v3_2_1/pa_cg_bom.xml"

set hdlType "Verilog"

set chains "CUSTOMIZE_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

# configure the IP
set result [source "C:/Xilinx/13.3/ISE_DS/PlanAhead/scripts/pa_cg_config_core.tcl"]

exit $result

