# Tcl script generated by PlanAhead

set tclUtilsPath "C:/Xilinx/13.3/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set cgProjectPath "C:/largework/fpga/kovan/kovan1/kovan1.srcs/sources_1/ip/clk_wiz_v3_2_1/coregen.cgc"

set ipName "clk_wiz_v3_2_qvga"

set hdlType "Verilog"

set cgPartSpec "6slx45-2csg324"

set chains "GENERATE_CURRENT_CHAIN"

set bomFilePath "C:/largework/fpga/kovan/kovan1/kovan1.srcs/sources_1/ip/clk_wiz_v3_2_1/pa_cg_bom.xml"

# generate the IP
set result [source "C:/Xilinx/13.3/ISE_DS/PlanAhead/scripts/pa_cg_gen_core.tcl"]

exit $result

